//Generated by pojo_create.js ... DO NOT EDIT!

package json;

public class PoJo {

    private int id;
    private String name;
    private String address;
    private Book book;

    public PoJo() {

    }

    public PoJo(int id, String name, String address, Book book) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.book = book;
    }

    public void setId(int id) {
        this.id = id;
    }
    public int getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    public void setBook(Book book) {
        this.book = book;
    }
    public Book getBook() {
        return this.book;
    }

}